language: php

# Only run on master branch and tags. PR must be activated on https://travis-ci.org/
# See https://stackoverflow.com/a/31882307
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# Versions to test
php:
 - 7.1
 - 7.2
 - 7.3

# Cache composer install
cache:
 directories:
   - $HOME/.composer/cache/files

# Update composer, install dependencies
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

# Commands to run
script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit --testsuite 'Unit'
  - ./vendor/bin/phpunit --testsuite 'Feature'

jobs:
  include:
    - stage: release
      script: php hours app:build --no-interaction
      deploy:
        provider: releases
        api_key:
          secure: "lFctstYi/0GYKXpl+Ng+Ry+V349qyHyeODkPfGj2/XdD7QphoSwjJrLUbkWOS5Y7x/xUTUZ3TPoGa/6yBFjMzV9zVlHgmPs7xXIZoZnRNWW6wf+yR8jklTE3cOq3QfBeCGS4tDDgQLdtpoNXol5pCDM1a2jGTtVEK/+gt34wTkG0zUaq/1RVDF3g9HdiJXHi4jeMuazDYsaghinQvqFs/g+JmVYV/eU4sChYi4KU5udbs1C10+IL8l4J0eRqqdjlmX3i86lkU1iJK2WBxo0QDOTMLduIYNqGjjJJ8UWcQJx7uZXzs33QOaHuwRASWiuZtbrUrfxZBPTkTZII0TZYhiirDimLRXk9bdzNcyKR6SwXjZMKQXSqz2IXNe4XcQeMtcxZT6+QU1BUG9L+lpXyEGZiD2zgOUH5S6D3EGFx6aXmvc96g7yihqsY3O/eYlxYmNrHJhIS4Mozj6PXw+9MDVo7rUyYhReW/lG8KsqqpsMxCeLrn2ZgeFeNyk9DgliFEkqlrK4lgjfwr/TmX0VjeEt8QxSiXVFhLfWHYEfEAczYGSC6jrQFxhfWO+7IPviXbWZpcbEKEO5XqRGRJqLyT5pgBocMtJ3/qx7rLL35LyJ+ykAhCnN/bPmeBMR5Jq32Zvx9XGoVNgI2U1hXZWg8IV/kmhopoaMXfn3SL1DC1nI="
        file: ./builds/hours
        skip_cleanup: true
        on:
          tags: true
